version: "3.8"

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

configs:
  registry_config_2024_04_16:
    file: ./configs/registry.yaml

networks:
  public:
    external: true
    name: public
    attachable: true

services:
  docker-registry:
    image: registry:2.8.3
    networks:
      - public
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      labels:
        caddy: "registry${DOMAIN_SUFFIX}.${DOMAIN_NAME:?err}"
        caddy.reverse_proxy: "{{ upstreams 5000 }}"
    volumes:
      - registry-data:/var/lib/docker-registry
      - ./configs/htpasswd:/htpasswd
    configs:
      - source: registry_config_2024_04_16
        target: /var/lib/registry/config.yml
    logging: *x-default-logging


volumes:
  registry-data:
