version: "3.8"

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  public:
    external: true
  agent_network:
    external: true

services:
  portainer-agent:
    image: portainer/agent:2.20.1-alpine
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      placement:
        constraints: [node.platform.os == linux]
    logging: *x-default-logging

  portainer:
    image: portainer/portainer-ce:2.20.1-alpine
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    networks:
      - public
      - agent_network
      - shared
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    logging: *x-default-logging
    deploy:
      replicas: 1
      mode: replicated
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
      placement:
        constraints:
          - node.role==manager
      labels:
        caddy: "portainer${DOMAIN_SUFFIX}.${DOMAIN_NAME:?err}"
        caddy.reverse_proxy: "{{upstreams 9000}}"
        caddy.authorize: with ghpolicy
volumes:
  portainer-data:
