version: "3.8"

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

# The following network is to be appended to every
# service that needs to be exposed to the outside world
networks:
  public:
    external: true
  shared:
    external: true
  caddy_controller:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.200.200.0/24"


services:
  minio:
    image: minio/minio:latest
    # restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/caddy && /usr/bin/minio server /data --console-address ":9001"'
    environment:
      # change once logged in
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - shared
      - public
    volumes:
      - type: bind
        source: ${HOME}/minio/data
        target: /data
    deploy:
      replicas: 1
      labels:
        # caddy: "minio${DOMAIN_SUFFIX}.${DOMAIN_NAME:-localhost}"
        proksi.enabled: "true"
        proksi.host: "minio${DOMAIN_SUFFIX}.${DOMAIN_NAME:-localhost}"
        proksi.port: "9001"
        proksi.ssl_certificate.self_signed_on_failure: "true"

        proksi.plugins.oauth2.provider: "github"
        proksi.plugins.oauth2.client_id: "${GITHUB_OAUTH_CLIENT_ID:-notSet}"
        proksi.plugins.oauth2.client_secret: "${GITHUB_OAUTH_CLIENT_SECRET:-notSet}"
        proksi.plugins.oauth2.jwt_secret: "${GITHUB_MIDDLEWARE_JWT_SECRET_KEY:-notSet}"
        proksi.plugins.oauth2.validations: |
          [ {  "type": "email", "value": ["${GITHUB_EMAIL:-notSet}"] } ]

      placement:
        constraints:
          - node.role == manager
    logging: *x-default-logging



  proksi:
    image: luizfonseca/proksi:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
      - shared
    environment:
      PROKSI_LOGGING__LEVEL: "debug"
      PROKSI_WORKER_THREADS: 2

      PROKSI_DOCKER__ENABLED: "true"
      PROKSI_DOCKER__MODE: "swarm"

      PROKSI_LETS_ENCRYPT__ENABLED: "true"
      PROKSI_LETS_ENCRYPT__STAGING: "true"
      PROKSI_LETS_ENCRYPT__EMAIL: "contact@vigio.net"

      PROKSI_PATHS__LETS_ENCRYPT: "/etc/proksi/certs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/etc/proksi/certs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    logging: *x-default-logging
