# https://grafana.com/docs/loki/latest/send-data/promtail/configuration/
# https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#docker_sd_config

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 2000000 # 2MB

scrape_configs:

  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        agent: promtail
        __path__: /var/log/*.log
        type: "system"

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_node_id']
        target_label: 'node'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['.request.host']
        target_label: 'http_host'
      - source_labels: ['.request.method']
        target_label: 'http_method'
    pipeline_stages:
      - static_labels:
          job: dockerlogs
          type: "docker"
          agent: promtail
