# ---------------------------------------
# Learn more about Vector configuration: https://vector.dev/docs/reference/configuration/

sources:
  sys_logs:
    type: "file"
    read_from: "beginning"
    ignore_older_secs: 600
    include: ["/var/log/ufw.log", "/var/log/auth.log"] # Include others if needed
    exclude: ["/var/log/docker/*"]

  docker_logs:
    type: "docker_logs"

transforms: 
  docker_parser:
    type: "remap"
    inputs: 
      - "docker_logs"
    source: |
      del(.source_type)
      .dt = del(.timestamp)
      .docker = del(.)
      .dt = del(.docker.dt)
      .message = del(.docker.message)
      .platform = "Docker"
      .lvl = "info"

      if exists(.level) {
        .lvl = del(.level)
      } 
sinks:
  loki_sink:
    type: "loki"
    buffer:
      type: "disk"
      max_size: 268435488 # 256MB
    endpoint: "http://olc_loki:3100"
    inputs: ["docker_parser"]
    encoding: 
      codec: "json"
    labels:
      agent: "vector"
      instance: '{{ docker.label."com.docker.swarm.task.id" }}'
      node: '{{ docker.label."com.docker.swarm.node.id" }}'
      service: '{{ docker.label."com.docker.swarm.service.name" }}'
      type: "docker"
      level: '{{ lvl }}'


  loki_sys_sink:
    type: "loki"
    buffer:
      type: "disk"
      max_size: 268435488 # 256MB
    endpoint: "http://olc_loki:3100"
    inputs: ["sys_logs"]
    encoding: 
      codec: "json"
    labels:
      agent: "vector"
      type: "system"